### ISSUE TITLE
yarn install failed

### ISSUE THREAD

**Issue by yong-asial** [OnsenUI/theme-roller#33]
```
➜  theme-roller git:(master) yarn install
yarn install v1.22.10
warning package.json: No license field
warning theme-roller@1.0.0: No license field
[1/5] 🔍  Validating package.json...
warning theme-roller@1.0.0: No license field
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
warning " > postcss-cssnext@3.0.2" has unmet peer dependency "caniuse-lite@^1.0.30000697".
[5/5] 🔨  Building fresh packages...
[-/3] ⡀ waiting...
[2/3] ⡀ fsevents
error /Users/asial/projects/onsenui/theme-roller/node_modules/chromedriver: Command failed.
Exit code: 1
Command: node install.js
Arguments:
Directory: /Users/asial/projects/onsenui/theme-roller/node_modules/chromedriver
Output:
Downloading https://chromedriver.storage.googleapis.com/2.33/chromedriver_mac64.zip
Saving to /var/folders/n7/92gmffp11j1fj4x35_knd8680000gn/T/chromedriver/chromedriver_mac64.zip
Received 782K...
Received 1568K...
Received 2352K...
Received 3136K...
Received 3920K...
Received 4704K...
Received 5299K total.
Extracting zip contents
/Users/asial/projects/onsenui/theme-roller/node_modules/kew/kew.js:189
  if (this._error || this._hasData) throw new Error("Unable to resolve or reject the same promise twice")
                                    ^

Error: Unable to resolve or reject the same promise twice
    at Promise.reject (/Users/asial/projects/onsenui/theme-roller/node_modules/kew/kew.js:189:43)
    at Request.<anonymous> (/Users/asial/projects/onsenui/theme-roller/node_modules/chromedriver/install.js:196:14)
    at Request.emit (node:events:513:28)
    at Request.onRequestError (/Users/asial/projects/onsenui/theme-roller/node_modules/request/request.js:878:8)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketErrorListener (node:_http_client:481:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
```

**Comment by emccorson** [comment]
I am not seeing this error at the moment. It might be a local setup problem. The main thing is that the theme-roller is building as part of the onsen.io CI build.

**Comment by as-hirose** [comment]
@emccorson It doesn't work on my environment, too. Could you tell us about your environment information like (node, yarn, npm...).

**Comment by yong-asial** [comment]
@emccorson It works with "npm" for "npm install". however, it is failed with "npm run build"

```
ERROR in ./build/pffsu-monkeypatch.js
Module not found: Error: Can't resolve 'postcss-font-family-system-ui/src/main.mjs' in '/Users/asial/projects/onsenui/theme-roller/build'
 @ ./build/pffsu-monkeypatch.js 1:17-70
 @ ./node_modules/postcss-cssnext/lib/features.js
 @ ./node_modules/postcss-cssnext/lib/index.js
 @ ./src/css-processor.js
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/App.vue
 @ ./src/App.vue
 @ ./src/main.js

ERROR in static/js/vendor.af588b37a61140d144ee.js from UglifyJs
Invalid assignment [./node_modules/postcss-values-parser/lib/parser.js:26,0][static/js/vendor.af588b37a61140d144ee.js:7440,26]

  Build failed with errors.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! theme-roller@1.0.0 build: `node build/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the theme-roller@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/asial/.npm/_logs/2022-09-29T03_50_48_450Z-debug.log
```

```
 ERROR  Failed to compile with 1 errors                                                                                                                                                                                                                     12:51:38 PM

This dependency was not found:

* postcss-font-family-system-ui/src/main.mjs in ./build/pffsu-monkeypatch.js

To install it, you can run: npm install --save postcss-font-family-system-ui/src/main.mjs
```

Something is missing here 

- https://github.com/OnsenUI/theme-roller/blob/master/build/pffsu-monkeypatch.js#L1
```
module.exports = require('postcss-font-family-system-ui/src/main.mjs').default;
```
and there is no module or file for postcss-font-family-system-ui ...

**Comment by emccorson** [comment]
Thanks for the report. I am investigating just now and I will update here as I go.

```
|--------------+---------+---------+--------------+--------------+----------------+---------------|
| OS           |    node |    yarn | yarn install | yarn run dev | yarn run build | yarn run test |
|--------------+---------+---------+--------------+--------------+----------------+---------------|
| NixOS 22.05  | 16.16.0 | 1.22.18 | ✓            |              |                |               |
| MacOS 12.1   | 16.17.0 | 1.22.19 | x            |              |                |               |
|              | 12.18.1 |         | x            |              |                |               |
| Ubuntu 20.10 | 16.17.1 | 1.22.19 | ✓            |              |                |               |
|--------------+---------+---------+--------------+--------------+----------------+---------------|
```

**Comment by emccorson** [comment]
Can you try node 8? I think it should work.

It looks like the tests were never written. There is just a dummy HelloWorld test so I am expecting `yarn run test` to fail.
@yong-asial @as-hirose

**Comment by yong-asial** [comment]
Thank you. It worked with Node 8. I'll close the ticket.
